#!c:\users\yacine_10\desktop\yy\eco\myenv1\scripts\python.exe
## -*- coding: utf-8 -*-
##
##  Jonathan Salwan - 2014-05-12 - ROPgadget tool
##
##  http://twitter.com/JonathanSalwan
##  http://shell-storm.org/project/ROPgadget/
##

import ropgadget

ropgadget.main()
