# Generated by Django 3.0.7 on 2023-12-03 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20231203_2338'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='product',
            field=models.ForeignKey(default='ert', on_delete=django.db.models.deletion.CASCADE, to='store.Variation'),
        ),
    ]
