# Generated by Django 3.0.7 on 2023-12-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20231204_0000'),
        ('stock', '0002_auto_20231203_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment_stockhistory',
            name='product',
            field=models.ForeignKey(default='erqq', on_delete=django.db.models.deletion.CASCADE, to='store.Variation'),
        ),
    ]
