# Generated by Django 3.0.7 on 2025-02-01 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliate', '0002_auto_20250201_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatereferral',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referraled', to=settings.AUTH_USER_MODEL),
        ),
    ]
