# Generated by Django 3.0.7 on 2025-02-01 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliate', '0003_auto_20250202_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatereferral',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referralled', to='affiliate.Affiliate'),
        ),
        migrations.AlterField(
            model_name='affiliatereferral',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrall', to=settings.AUTH_USER_MODEL),
        ),
    ]
