# Generated by Django 3.0.7 on 2025-02-04 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_auto_20250202_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_link', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('social_media', 'Social Media'), ('website', 'Website'), ('email', 'Email Marketing'), ('other', 'Other')], max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.Affiliate')),
            ],
        ),
    ]
