# Generated by Django 3.0.7 on 2025-02-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0005_affiliateclick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='commission_rate',
        ),
    ]
