# Generated by Django 3.0.7 on 2025-02-05 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20250205_0138'),
        ('affiliate', '0006_remove_affiliate_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
