# Generated by Django 3.0.7 on 2025-02-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0007_affiliate_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatecommission',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
