# Generated by Django 3.0.7 on 2023-11-21 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_slide',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 0, 21, 49, 858764, tzinfo=utc)),
        ),
    ]
