# Generated by Django 3.0.7 on 2024-01-26 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_slide',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 9, 18, 35, 473273, tzinfo=utc)),
        ),
    ]
