# Generated by Django 3.0.7 on 2023-12-03 23:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20231203_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_slide',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 23, 0, 42, 753515, tzinfo=utc)),
        ),
    ]
