# Generated by Django 3.0.7 on 2024-01-27 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20240126_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_slide',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 20, 2, 13, 584368, tzinfo=utc)),
        ),
    ]
