# Generated by Django 3.0.7 on 2024-01-27 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20240127_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroomproduct',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='chatroomproduct',
            name='product_rome',
        ),
        migrations.AlterField(
            model_name='daily_slide',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 20, 9, 7, 510969, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoomProduct',
        ),
    ]
