# Generated by Django 3.0.7 on 2025-02-04 22:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20250204_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_and_outlet',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 22, 43, 42, 84734, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daily_slide',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 22, 43, 42, 84734, tzinfo=utc)),
        ),
    ]
