# Generated by Django 3.0.7 on 2025-02-04 23:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20250205_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='commission_rate',
        ),
        migrations.AlterField(
            model_name='daily_and_outlet',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 23, 12, 56, 748062, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daily_slide',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 23, 12, 56, 747061, tzinfo=utc)),
        ),
    ]
