# Generated by Django 3.0.7 on 2025-02-04 23:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20250205_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='is_affiliate_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='daily_and_outlet',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 23, 56, 41, 346840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daily_slide',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 23, 56, 41, 345839, tzinfo=utc)),
        ),
    ]
