# Generated by Django 3.0.7 on 2024-01-31 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20240131_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_slide',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 19, 43, 38, 200971, tzinfo=utc)),
        ),
    ]
