# Generated by Django 3.0.7 on 2025-02-13 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20250213_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, null=True, upload_to='files/products/digital_files'),
        ),
        migrations.AlterField(
            model_name='daily_and_outlet',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 19, 22, 16, 645035, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daily_slide',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 19, 22, 16, 645035, tzinfo=utc)),
        ),
    ]
