# Generated by Django 3.0.7 on 2025-02-18 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20250216_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_and_outlet',
            name='expiration_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daily_slide',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 20, 19, 27, 27, 567965, tzinfo=utc)),
        ),
    ]
