# Generated by Django 3.0.7 on 2025-02-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20250218_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallery', 'verbose_name_plural': 'product galleries'},
        ),
        migrations.AddField(
            model_name='productgallery',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='store/products'),
        ),
    ]
