# Generated by Django 3.0.7 on 2025-02-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
