# Generated by Django 3.0.7 on 2025-03-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_confirmation_code_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
