# Generated by Django 3.0.7 on 2025-03-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20250303_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number_verified',
        ),
        migrations.RemoveField(
            model_name='account',
            name='verification_code',
        ),
    ]
