"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from django.utils.translation import gettext_lazy as _ #to add en fr ar lnguges
from pathlib import Path
import os
import pdfkit
from django.contrib.messages import constants as messages
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent





# Secret Key










# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

#thumbnail
THUMBNAIL_ENGINE = 'sorl.thumbnail.engines.pil_engine.Engine'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'category',
    'accounts',
    'store',
    'carts',
    'orders',
    'products',
    'blog',
    'sorl.thumbnail',
    'tinymce',
    'newsletter',
    'printing',
    'social',
    'social_django',
    'cities_light',

    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.AdminLocaleMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',

]

ROOT_URLCONF = 'ecommerce.urls'

ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

SITE_ID = 1



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'category.context_processors.menu_links',
                'carts.context_processors.counter',
                'carts.context_processors.Items',
                'store.context_processors.wishlist_count',
                'accounts.context_processors.user_profile_picture',
                'orders.context_processors.seller_order_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'
# this setting do it, when i use a Account Apps
AUTH_USER_MODEL = 'accounts.Account'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}






# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/



TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = True



LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
    ('fr', _('French')),
    
    
]




LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'assets')]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')






MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}



# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_PASSWORD')
EMAIL_USE_TLS = True


TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': 600,
    'menubar': True,
    'plugins': 'advlist autolink lists link image charmap print preview anchor',
    'toolbar': 'a11ycheck | formatselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
    
}



# for pdf 
WKHTMLTOPDF_CMD = r'C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe'
pdfkit_config = pdfkit.configuration(wkhtmltopdf=WKHTMLTOPDF_CMD)





AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    # Add other social media backends as needed
    'django.contrib.auth.backends.ModelBackend',  # Django's default authentication backend
)

SOCIAL_AUTH_FACEBOOK_KEY = '1490753381680490'
SOCIAL_AUTH_FACEBOOK_SECRET = 'ead47101878cab139d5bef497ee1f02e'

SOCIAL_AUTH_TWITTER_KEY = 'YOUR_TWITTER_APP_KEY'
SOCIAL_AUTH_TWITTER_SECRET = 'YOUR_TWITTER_APP_SECRET'
# Add configuration for other social media platforms





# to add city and re# Specify the settings for the 'cities_light' app
# Specify the settings for the 'cities_light' app
CITIES_LIGHT_TRANSLATION_LANGUAGES = ['en']  # Use the language you prefer

# Add 'cities_light' data import command to the list of commands
MIGRATION_MODULES = {
    'cities_light': 'cities_light.migrations',
}

# Use the 'cities_light' models for state and city selection in your form
CITIES_LIGHT_INCLUDE_COUNTRIES = ['DZ']  # Add Algeria's country code

# Enable the use of `django-cities-light` for your project
CITIES_LIGHT_FUNCTION_TRANSLIT = 'cities_light.translit_ascii'

# Ensure that 'cities_light' data is loaded during migrations
CITIES_LIGHT_APPENDBUTTON = True

# Use the 'model' search mode for better performance (default is 'city')
#CITIES_LIGHT_SEARCH_MODE = 'model'

# Specify the location of your 'cities_light' data files
CITIES_LIGHT_DATA_FILES = {
    'city': {
        'filename': 'date/DZ.txt',  # Change to your actual file
        'urls': [],  # Use appropriate source
    },
    'region': {
        'filename': 'your_region_data_file.txt',  # Change to your actual file
        'urls': [],  # Use appropriate source
    },
}

