# Generated by Django 3.0.7 on 2025-02-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='video',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
    ]
