# Generated by Django 3.0.7 on 2025-02-27 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicite', '0002_auto_20250223_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-start_date'], 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10, verbose_name='Ad Type'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/images/', verbose_name='Ad Image'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='impressions',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the ad has been viewed', verbose_name='Impressions'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='link',
            field=models.URLField(blank=True, help_text='Optional URL to redirect when clicked', verbose_name='Redirect URL'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Advertisement Title'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Optional YouTube video link', null=True, verbose_name='YouTube Link'),
        ),
        migrations.CreateModel(
            name='SlideAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the slide', verbose_name='Slide Order')),
                ('duration', models.PositiveIntegerField(default=5, help_text='Duration in seconds the ad will be displayed', verbose_name='Slide Duration')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_ads', to='publicite.Advertisement', verbose_name='Advertisement')),
            ],
            options={
                'verbose_name': 'Slide Advertisement',
                'verbose_name_plural': 'Slide Advertisements',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ColumnAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, help_text='Position of the ad in the column layout', verbose_name='Column Position')),
                ('width', models.PositiveIntegerField(choices=[(1, '1/12'), (2, '2/12'), (3, '3/12'), (4, '4/12'), (5, '5/12'), (6, '6/12'), (7, '7/12'), (8, '8/12'), (9, '9/12'), (10, '10/12'), (11, '11/12'), (12, '12/12')], default=4, help_text='Width of the ad in the grid (1-12 columns)', verbose_name='Ad Width')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_ads', to='publicite.Advertisement', verbose_name='Advertisement')),
            ],
            options={
                'verbose_name': 'Column Advertisement',
                'verbose_name_plural': 'Column Advertisements',
                'ordering': ['position'],
            },
        ),
    ]
