# Generated by Django 3.0.7 on 2025-02-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicite', '0003_auto_20250227_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnadvertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/columns/', verbose_name='Column Image'),
        ),
        migrations.AddField(
            model_name='slideadvertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/slides/', verbose_name='Slide Image'),
        ),
    ]
