# Generated by Django 3.0.7 on 2025-02-27 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicite', '0004_auto_20250227_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/images/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='impressions',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the ad has been viewed'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='link',
            field=models.URLField(blank=True, help_text='Optional URL to redirect when clicked'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
    ]
