# Generated by Django 3.0.7 on 2025-02-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicite', '0005_auto_20250227_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideadvertisement',
            name='advertisement',
        ),
        migrations.DeleteModel(
            name='ColumnAdvertisement',
        ),
        migrations.DeleteModel(
            name='SlideAdvertisement',
        ),
    ]
