# Generated by Django 3.0.7 on 2025-02-01 20:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City_Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(max_length=20)),
                ('order_note', models.CharField(blank=True, max_length=100)),
                ('shipping_total', models.FloatField()),
                ('order_total', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_method', models.CharField(choices=[('home', 'Home Delivery'), ('pickup', 'Pick Up from Delivery Bureau')], default='home', max_length=10)),
                ('pickup_location', models.CharField(choices=[('yalidine', 'Yali Dine'), ('KaziTour', 'Kazi Tour'), ('turktour', 'Turk Tour'), ('expres', 'Expres'), ('rapidtour', 'Rapid Tour')], default='Home', max_length=10)),
                ('payment_method', models.CharField(choices=[('cib', 'Credit Bank Card (CIB)'), ('edahabia', 'Card Manitique'), ('cod', 'Cash on Delivery')], default='cod', max_length=20)),
                ('promotion_discount', models.FloatField(blank=True, null=True)),
                ('coupon_discount', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('total_shipping_cost', models.FloatField(blank=True, null=True)),
                ('is_guest', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
