# Generated by Django 3.0.7 on 2025-02-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_auto_20250202_0050'),
        ('orders', '0002_auto_20250201_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchased_through_affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_orders', to='affiliate.Affiliate'),
        ),
    ]
