# Generated by Django 3.0.7 on 2025-03-06 03:08

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='SEO Title for the page.', max_length=255)),
                ('description', models.TextField(help_text='Meta description for the page.')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=500)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for the page.', null=True)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title.', max_length=255)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description.')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image.', null=True, upload_to='seo/')),
                ('og_url', models.URLField(blank=True, help_text='Open Graph URL.', null=True)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter Card title.', max_length=255)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter Card description.')),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter Card image.', null=True, upload_to='seo/')),
                ('structured_data', jsonfield.fields.JSONField(blank=True, help_text='JSON-LD structured data.', null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
